# if dont want to mess with your os env
version: '2.1'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.local
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      db_name: springboot_demo
      db_username: root
      db_password: IIIdevops123!
      db_host: db
    ports:
      - 8080
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/employees"]
        interval: 180s
        timeout: 5s
        retries: 5
  db:
    image: 'bitnami/mariadb:10.5-debian-10'
    restart: always
    environment:
      MARIADB_DATABASE: springboot_demo
      MARIADB_ROOT_PASSWORD: IIIdevops123!
    volumes:
      - ./db:/docker-entrypoint-initdb.d:rw
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 30s
      timeout: 10s
      retries: 6
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080
  ## 如果沒有要用網頁進行測試RESTAPI的話可以註解掉下方功能
  swaggereditor:
    image: swaggerapi/swagger-editor
    ports:
      - 8080
    volumes:
      - ./app:/tmp
    environment:
      - SWAGGER_FILE=/tmp/openapi_local.yaml
  # 如果沒有要跑Postman-collection(newman)的話可以註解掉下方功能
  postman_collection:
    image: postman/newman
    depends_on:
      web:
        condition: service_healthy
    volumes:
      - ./app:/etc/postman:rw
    command:
      - "run"
      - "/etc/postman/postman_collection_local.json"
      - "--reporters"
      - "junit"
      - "--reporter-junit-export=/etc/postman/newman-report.xml"
      - "--delay-request"
      - "1000"
  # owasp
  owasp:
    image: owasp/zap2docker-stable
    depends_on:
      web:
        condition: service_healthy
    volumes:
      - ./app:/zap/wrk/:rw
    tty: true
    command: bash -c "
        sleep 30 && 
        zap-api-scan.py -t openapi_local.yaml -w owasp-report.md -g gen.conf -f openapi
      "
